# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3c333541b1807a90350f6d829e13cd9b"
name = "my-shop-app"
handle = "my-shop-app-41"
application_url = "https://5d6c-2406-7400-c8-90b6-f1cf-6ee3-6175-c6bc.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "onlinestorehelper.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = [
  "https://5d6c-2406-7400-c8-90b6-f1cf-6ee3-6175-c6bc.ngrok-free.app/auth/callback",
  "https://5d6c-2406-7400-c8-90b6-f1cf-6ee3-6175-c6bc.ngrok-free.app/auth/shopify/callback",
  "https://5d6c-2406-7400-c8-90b6-f1cf-6ee3-6175-c6bc.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true
